In [1]:
import sklearn.datasets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

data=pd.read_csv('banknote.csv', encoding='latin')
data.head()

variance of Wavelet  skewness of Wavelet  curtosis of Wavelet  entropy  \
0              3.62160               8.6661              -2.8073 -0.44699   
1              4.54590               8.1674              -2.4586 -1.46210   
2              3.86600              -2.6383               1.9242  0.10645   
3              3.45660               9.5228              -4.0112 -3.59440   
4              0.32924              -4.4552               4.5718 -0.98880   

   class  
0    1.0  
1    1.0  
2    1.0  
3    1.0  
4    1.0

# Bootstrap

## scipy.stats.bootstrap, for calculating a static value

## https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bootstrap.html

In [2]:
print('mean:',np.mean(data['entropy']))

mean: -1.1916565211370262


In [3]:
a=data['entropy']
a=(a,)  ### important, bootstrap(data,....,)  data need to be of type of tuple
a

(0      -0.44699
 1      -1.46210
 2       0.10645
 3      -3.59440
 4      -0.98880
          ...   
 1367   -0.55949
 1368    0.34179
 1369   -2.77710
 1370   -1.28230
 1371    1.19520
 Name: entropy, Length: 1372, dtype: float64,)

In [4]:
from scipy.stats import bootstrap

In [5]:
res = bootstrap(a,  ## need to be tuple
                np.mean,
                n_resamples=1000, # times of resamples
                # axis = 0,  #default
                confidence_level=0.9,method='percentile')


print((res.confidence_interval[0]+res.confidence_interval[1])/2)
print(res.confidence_interval)


-1.1946459487973762
ConfidenceInterval(low=-1.2920979236151602, high=-1.097193973979592)


## use bootstrap on a dataset

## https://scikit-learn.org/stable/modules/generated/sklearn.utils.resample.html

In [6]:
from sklearn.utils import resample

data_test=[1,2,3,4,5,6,7,8,9,10]
boot_test = resample(data_test, replace=True, n_samples=len(data_test)//5*4, random_state=2)
print('Bootstrap Sample: %s' % boot_test)
# out of bag observations
oob = [x for x in data_test if x not in boot_test]
print('OOB Sample: %s' % oob)

Bootstrap Sample: [9, 9, 7, 3, 9, 8, 3, 2]
OOB Sample: [1, 4, 5, 6, 10]


In [7]:
data.head()

variance of Wavelet  skewness of Wavelet  curtosis of Wavelet  entropy  \
0              3.62160               8.6661              -2.8073 -0.44699   
1              4.54590               8.1674              -2.4586 -1.46210   
2              3.86600              -2.6383               1.9242  0.10645   
3              3.45660               9.5228              -4.0112 -3.59440   
4              0.32924              -4.4552               4.5718 -0.98880   

   class  
0    1.0  
1    1.0  
2    1.0  
3    1.0  
4    1.0

In [8]:
boot = resample(data, replace=True, n_samples=len(data)//5*4, random_state=2)
boot


variance of Wavelet  skewness of Wavelet  curtosis of Wavelet  entropy  \
1192             -4.40180             -12.9371             15.65590 -1.68060   
527               2.53280               7.5280             -0.41929 -2.64780   
493               2.80840              11.3045             -3.33940 -4.41940   
299               2.29280               9.0386             -3.24170 -1.29910   
466               1.14720               3.5985              1.93870 -0.43406   
...                   ...                  ...                  ...      ...   
647               3.77910               2.5762              1.30980  0.56550   
1083             -0.69879              -3.3771              4.12110  1.50430   
1278              0.53936               3.8944             -4.81660 -4.34180   
793              -2.28600              -5.4484              5.80390  0.88231   
1217              0.61652               3.8944             -4.72750 -4.39480   

      class  
1192    2.0  
527     1.0  
493     1.0  
299     1.0  
466     1.0  
...     ...  
647     1.0  
1083    2.0  
1278    2.0  
793     2.0  
1217    2.0  

[1096 rows x 5 columns]

In [10]:
# out of bag observations
oob=pd.DataFrame(columns=data.columns)


print(len(data))
print(len(boot))
print(len(set(boot.index)))

a=np.zeros(len(data))
for i in list(boot.index):
    a[i]=1

for i in range(len(data)):
    if a[i]==0:
        oob.loc[i]=list(data.loc[i].values)
        
print(len(oob))
oob

1372
1096
778
594


variance of Wavelet  skewness of Wavelet  curtosis of Wavelet  entropy  \
2                3.866000              -2.6383              1.92420  0.10645   
3                3.456600               9.5228             -4.01120 -3.59440   
4                0.329240              -4.4552              4.57180 -0.98880   
6                3.591200               3.0129              0.72888  0.56421   
7                2.092200              -6.8100              8.46360 -0.60216   
...                   ...                  ...                  ...      ...   
1354            -3.392400               3.3564             -0.72004 -3.52330   
1355            -6.163200               8.7096             -0.21621 -3.63450   
1357            -2.589900              -0.3911              0.93452  0.42972   
1359             0.066129               2.4914             -2.94010 -0.62156   
1364            -2.839100              -6.6300             10.48490 -0.42113   

      class  
2       1.0  
3       1.0  
4       1.0  
6       1.0  
7       1.0  
...     ...  
1354    2.0  
1355    2.0  
1357    2.0  
1359    2.0  
1364    2.0  

[594 rows x 5 columns]

# use bootstrap to evaluate a model, use bootstrap to give train set , test sest

In [11]:
data.head()

variance of Wavelet  skewness of Wavelet  curtosis of Wavelet  entropy  \
0              3.62160               8.6661              -2.8073 -0.44699   
1              4.54590               8.1674              -2.4586 -1.46210   
2              3.86600              -2.6383               1.9242  0.10645   
3              3.45660               9.5228              -4.0112 -3.59440   
4              0.32924              -4.4552               4.5718 -0.98880   

   class  
0    1.0  
1    1.0  
2    1.0  
3    1.0  
4    1.0

In [12]:
Feature_names=list(data.columns[:-1])
print(Feature_names)
Target=data.columns[-1]
print(Target)

['variance of Wavelet', 'skewness of Wavelet', 'curtosis of Wavelet', 'entropy']
class


In [13]:
X=data[Feature_names]
y=data[Target]

### if we dived the whole dataset into train set (bootstrap)and test set(all instances out of bag)

In [14]:


boot = resample(data, replace=True, n_samples=len(data)//5*4)

oob=pd.DataFrame(columns=data.columns)
a=np.zeros(len(data))
for i in list(boot.index):
    a[i]=1
for i in range(len(data)):
    if a[i]==0:
        oob.loc[i]=list(data.loc[i].values)
        

X_train = boot[Feature_names]
y_train = boot[Target]

X_test = oob[Feature_names]
y_test = oob[Target]

In [15]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')

print(clf)

DTree=clf.fit(X_train,y_train)
prediction=DTree.predict(X_test)

from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))




DecisionTreeClassifier(max_depth=4)
              precision    recall  f1-score   support

         1.0       0.97      0.94      0.96       355
         2.0       0.92      0.96      0.94       249

    accuracy                           0.95       604
   macro avg       0.95      0.95      0.95       604
weighted avg       0.95      0.95      0.95       604

[[334  21]
 [ 10 239]]
Accuracy of the model on Testing Sample Data: 0.95


In [16]:
ERR=0
TIMES =10
for i in range(TIMES):

    boot = resample(data, replace=True, n_samples=len(data)//5*4)

    oob=pd.DataFrame(columns=data.columns)
    a=np.zeros(len(data))
    for i in list(boot.index):
        a[i]=1
    for i in range(len(data)):
        if a[i]==0:
            oob.loc[i]=list(data.loc[i].values)


    X_train = boot[Feature_names]
    y_train = boot[Target]

    X_test = oob[Feature_names]
    y_test = oob[Target]
    clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')


    DTree=clf.fit(X_train,y_train)
    prediction=DTree.predict(X_test)
    
    err=0
    for i in prediction!=y_test:
        if i:
            err+=1
    err=err/len(y_test)
    ERR+=err
ERR/=TIMES
    
print("Final accuracy:",1-ERR)


Final accuracy: 0.9504479805215863


## remark: it works, but is not very practic, when the dataset is big, because we need to find all instances out of bags to form the test est, it costs much time

## If we divide the dataset into train set and test set at the begining, and then use bootstrap to the trainset

In [135]:
from sklearn.model_selection import train_test_split
data_train, data_test = train_test_split(data, test_size=0.2, random_state=428)


In [136]:
boot = resample(data_train ,replace=True, n_samples=len(data_train)//5*4)

In [145]:
X_train = boot[Feature_names]
y_train = boot[Target]

X_test = data_test[Feature_names]
y_test = data_test[Target]

In [146]:
clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')

print(clf)

DTree=clf.fit(X_train,y_train)
prediction=DTree.predict(X_test)

from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))


DecisionTreeClassifier(max_depth=4)
              precision    recall  f1-score   support

         1.0       0.91      0.98      0.95       150
         2.0       0.97      0.89      0.93       125

    accuracy                           0.94       275
   macro avg       0.94      0.93      0.94       275
weighted avg       0.94      0.94      0.94       275

[[147   3]
 [ 14 111]]
Accuracy of the model on Testing Sample Data: 0.94


In [147]:
ERR=0
TIMES =10
for i in range(TIMES):

    boot = resample(data_train, replace=True, n_samples=len(data_train)//10*9)

    X_train = boot[Feature_names]
    y_train = boot[Target]
    clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')


    DTree=clf.fit(X_train,y_train)
    prediction=DTree.predict(X_test)
    
    err=0
    for i in prediction!=y_test:
        if i:
            err+=1
    err=err/len(y_test)
    ERR+=err
ERR/=TIMES
    
print("Final accuracy:",1-ERR)


Final accuracy: 0.9472727272727273


## if we use the average prediction of bootstrap to be the final prediction (Bagging)

In [152]:
TIMES =20
Prediction= np.zeros(len(y_test))

for i in range(TIMES):

    boot = resample(data, replace=True, n_samples=len(data)//4)

    X_train = boot[Feature_names]
    y_train = boot[Target]

    clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')

    DTree=clf.fit(X_train,y_train)
    prediction=DTree.predict(X_test)
    Prediction+=prediction

Prediction/=TIMES
for i in range(len(Prediction)):
    if Prediction[i]>1.5:
        Prediction[i]=2
    else:
        Prediction[i]=1
        

        
print(metrics.classification_report(y_test, Prediction))
print(metrics.confusion_matrix(y_test, Prediction))

F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))



              precision    recall  f1-score   support

         1.0       0.99      0.99      0.99       150
         2.0       0.98      0.98      0.98       125

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275

[[148   2]
 [  2 123]]
Accuracy of the model on Testing Sample Data: 0.96


## Remark

## A lot of methods of machine leaning has already used the bootstrap in the process of training, Bootstrap Aggregation (Bagging) .

## random forest, xgboosyt use Bagging

# Other resample methods in machine learning
# Cross validation 

In [125]:
data_train, data_test = train_test_split(data, test_size=0.2, random_state=428)
X_train = data_train[Feature_names]
y_train = data_train[Target]

X_test = data_test[Feature_names]
y_test = data_test[Target]

In [126]:
clf = tree.DecisionTreeClassifier(max_depth=4,criterion='gini')

print(clf)

DTree=clf.fit(X_train,y_train)
prediction=DTree.predict(X_test)

from sklearn import metrics
print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

F1_Score=metrics.f1_score(y_test, prediction, average='weighted')
print('Accuracy of the model on Testing Sample Data:', round(F1_Score,2))

from sklearn.model_selection import cross_val_score

# Running 10-Fold Cross validation on a given algorithm
# Passing full data X and y because the K-fold will split the data and automatically choose train/test
Accuracy_Values=cross_val_score(DTree, X , y, cv=10, scoring='f1_weighted')
print('\nAccuracy values for 10-fold Cross Validation:\n',Accuracy_Values)
print('\nFinal Average Accuracy of the model:', round(Accuracy_Values.mean(),2))

DecisionTreeClassifier(max_depth=4)
              precision    recall  f1-score   support

         1.0       0.95      0.98      0.96       150
         2.0       0.97      0.94      0.96       125

    accuracy                           0.96       275
   macro avg       0.96      0.96      0.96       275
weighted avg       0.96      0.96      0.96       275

[[147   3]
 [  8 117]]
Accuracy of the model on Testing Sample Data: 0.96

Accuracy values for 10-fold Cross Validation:
 [0.95652174 0.96387342 0.91947296 0.9562656  0.95620438 0.91947296
 0.96357419 0.98540146 0.96357419 0.93411424]

Final Average Accuracy of the model: 0.95
